import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Garrage Nepal",
    // template: "%s - Garrage Nepal",
  },
  description: "Generated by Dipendra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {/* <Navigation /> */}
        {/* <Header /> */}
        <header

          className="font-bold bg-red-400 text-2xl">
          <Link href='/' replace>
            <p>Header</p></Link>
        </header>
        {children}
        <h1>Footer</h1>
      </body>
    </html>
  );
}
