import Link from 'next/link'
import React from 'react'


export const metadata = {
  title: "home page",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className='p-5 space-y-3'>
      {/* movies list */}
      <div>

        <h2 className='text-xl'>Home page</h2>
        <Suspense fallback={<Loading />
        }>
          <MovieList />
        </Suspense>

      </div>


    </div>
  )
}
