import React, { Suspense } from 'react'
import MovieList from './movies/MovieList';
import Loading from './movies/Loading';


export const metadata = {
  title: "home page",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className='p-5 space-y-3'>
      {/* movies list */}
      <div>

        <h2 className='text-xl'>Home page</h2>
        <Suspense fallback={<Loading />
        }>
          <MovieList />
        </Suspense>

      </div>


      {/* childs */}
      <Childs>
      </Childs>
    </div>
  )
}

export default page

const Childs = ({ children }) => {
  return (<div>
    <h1>Welcome to movie list</h1>
    {children}


  </div>)
}