import React from 'react'

export const metadata: Metadata = {
  title: "home page",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Childs>
        hello man
      </Childs>
    </div>
  )
}

export default page

const Childs = ({ children }) => {
  return (<div>
    <h1>Childs</h1>
    {children}


  </div>)
}