import axios from "axios"
import { Metadata } from "next";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Movies data",
  description: "Generated by create next app",
};

const getData = async () => {
  const res = await fetch('https://6758f6c060576a194d129152.mockapi.io/movies', {
    next: {
      revalidate: 10 //updaing data in long time not rea time 
    }

  });
  return res.json();
}
const MovieList = async () => {
  const res = await getData();
  // console.log(res);

  return (
    <div>
      5Movies
      {res && res.map((val) => {
        return <Link href={`/movies/${val.id}`} key={val.id} className="flex flex-col p-4 shadow-2xl bg-blue-300  ">
          <img
            className="h-[399px] w-[399px]"
            src={val.Poster} alt="" />

          <h1 className="text-xl">S.N :{val.id}</h1>
          <h1 className="text-xl">Title :{val.Title}</h1>
          <h2 className="text-xl">Released year: {val.Year}</h2>
          <h2 className="text-xl">Runtime time :{val.Runtime}</h2>



        </Link>
      })

      }

    </div>
  )
}

export default MovieList
